Repository lanl/ports-of-call, pull requests merged in 2024-08, with the labels that each got.

#49 Add automation to formatting and extend development docs
  .clang-format
  CMakeLists.txt
  cmake/Format.cmake
  doc/sphinx/src/developing.rst
  ports-of-call/portability.hpp
  ports-of-call/portable_arrays.hpp
  ports-of-call/portable_errors.hpp
  script/format.sh
  test/test_portsofcall.cpp
Labels: documentation, Build

#52 add CI tests and add catch v3 to spackage
  .github/workflows/tests-minimal.yml
  spack-repo/packages/ports-of-call/package.py
Labels: enhancement, Build

#48 Transfer array from Singe
  doc/sphinx/src/using.rst
  ports-of-call/array.hpp
  test/CMakeLists.txt
  test/test_array.cpp
Labels: enhancement
